### ISSUE TITLE
Menu aanmaken error

### ISSUE THREAD

**Issue by bvdn** [jessedobbelaere/fork-cms-module-menu#1]
Backend: Categorien aangemaakt, 
daarna bij menu aanmaken en dan krijg ik deze <hoofd>melding

ContextErrorException: Notice: Undefined index: item in /src/Backend/Cache/CompiledTemplates/0bd18c7fcfbd357de211660335d281e8_Add.tpl.php line 54

btw: de 'a la carte' werkt wel weer naar behoren.

**Comment by jessedobbelaere** [comment]
Kan je de CompiledTemplates cache map eens leegmaken? 
Ik heb zonet de module eens geïnstalleerd op Fork CMS 3.8.7 (recentste versie) en daar werkt het aanmaken van categorieën en daarna menu aanmaken zoals het hoort. Ook à la carte.
Heb het ook eens geïnstalleerd via FTP op een installatie van fork cms en ook daar kan ik het probleem niet zien...

**Comment by bvdn** [comment]
Cache leeggemaakt, maar menu-item aanmaken lukt nog niet. Krijg dezelfde melding.

Heb ook een nieuwe installatie 387 gemaakt en daar doet de module het wel. < alleen als je de categorieën verwijdert, geeft ie een 500 melding > maar hij verwijdert ze wel, dus e.e.a. functioneert.
Vreemd..

**Comment by jessedobbelaere** [comment]
Ik kan niet onmiddellijk iets bedenken dat het probleem zou kunnen veroorzaken. Werk je met debug mode ingeschakeld?

Ik heb normaal gezien de bug opgelost die ervoor zorgde dat categorieën verwijderen een error gaf, probeer anders de recentste versie eens.

**Comment by bvdn** [comment]
ik heb 387 geïnstalleerd en daar  komt de bug 'categorieen' weghalen niet voor.

**Comment by bvdn** [comment]
kijk eens naar: http://www.387.burovandernet.nl/widget-menu-pagina 

Item 1 deze link werkt
Item 2 deze link gaat nergens heen?
item 3 deze link gaat nergens heen?

kijk eens naar: http://www.387.burovandernet.nl/menu-a-la-carte
klopt het dat je de a la carte regelt in de menu module, maar dat ie niet 'communiceert' met de categorie en de menu van de module? De a la carte vul je apart in?

**Comment by jessedobbelaere** [comment]
De module zorgt voor bruikbare html code, maar er is geen css en javascript voorzien. Op [deze site](http://restaurant.woestyne.be/nl/menu) werkte ik steeds met tabbladen tussen de menu's. Je kan daarvoor bv dit stuk js gebruiken:

```
// Tabs
$('.menu-tabs a').click(function (e) {
    e.preventDefault();
    $(this).tab('show');
    return false;
});
```

En eveneens [deze javascript library](http://restaurant.woestyne.be/src/Frontend/Themes/woestyne/Core/Js/tabs.js) inladen voordat je dit stuk code gebruikt.

Ik zie dat alle 3 de items in de html code staan, maar ze zijn verborgen. Als je op de naam van item 2 of 3 klikt, zorgt de javascript ervoor dat ze actief worden. Je kan de css code gebruiken van de Woestyne website die ik maakte indien je een soortgelijk resultaat wilt qua uitzicht op de menu en à la carte.

Het klopt dat à la carte niet verbonden is met de menu, aangezien ik deze module voor een klant gemaakt heb en dat de gerechten uit à la carte niet noodzakelijk in de menu voorkomen. De menu's bestaan dus gewoon uit tekst die je kan weergeven op de website.

**Comment by bvdn** [comment]
Hoi Jesse, 

bedankt voor je reactie.

kun je me aangeven waar ik de //Tabs js  en de library plaats?

Alvast bedankt.
GrG

**Comment by jessedobbelaere** [comment]
De tabs.js library zit al verwerkt in je theme die je gebruikt (bootstrap.js) dus die hoef je denk ik niet meer toe te voegen. De 5 lijntjes javascript code die ik gepost heb, kan je eventueel in de file "Core/Js/boots.js" zetten die je kan terugvinden in je bootstrap thema

**Comment by bvdn** [comment]
;-)

thanx a mil.
hij werkt!

GrG

Op 18 feb. 2015, om 17:14 heeft Jesse Dobbelaere <notifications@github.com <mailto:notifications@github.com>> het volgende geschreven:

**Comment by jessedobbelaere** [comment]
No problem :+1:
